### ISSUE TITLE
attachments

### ISSUE THREAD

**Issue by thomaspeterseil** [nmalkin/multimail#5] opened 2017-11-09 13:38 UTC
i tried to run the script to send out individual attachments using the placeholder in the batch.cfg file.
but the script sends to all the attachment from the first recipient.
i tried to add with the same placeholder the name of the attachment file in the mailbody as a text and that works fine, each recipient has the correct attachment-filename in the mailbody. but as attachment it doesnt work.

**Comment by nmalkin** [comment] 2017-11-09 20:25
Hmm, sorry to hear it's having problems. The customized attachments used to work, but, as you can tell, I haven't touched this project in a number of years.

Would you be able to provide me with sample config/other files that I can use to reproduce the issue? Also let me know which version of Mutt you're using.

Cheers!

**Comment by thomaspeterseil** [comment] 2017-11-09 20:49
hi,
thank you so much for your fast response!
i am using Mutt 1.5.24

here are my config files:

batch.cfg
---------

[common]
subject: QR-Codes with links
cc:
bcc:
attachment:<2>

----------
message.txt
----------

Hallo <1>,

some random text

in the attachment you can find this file: <2>

best,
thomas

-----------
recipients.csv
-----------

email-address1,Thomas,1.png
email-address2,thomas,2.png
email-address3,Thomas,3.png

--------------
thats my actual config. (i just removed the email adresses from my real config and wrote here email-address1,2,3)

if you want, i can set up a demo install on a digitalocean instance and give you an ssh account for testing.

once again thank you so much!
best,
thomas

**Comment by nmalkin** [comment] 2017-11-09 21:47
Thanks! There was a bug, which is now fixed (c27438c).

Fun fact: it looks like this was kindly fixed but then immediately reverted in #2.

Thanks for reporting, and hope it works for you now!

**Closed by nmalkin** 2017-11-09 21:47 UTC

**Comment by nmalkin** [comment] 2017-11-09 21:54
It looks like it was also fixed — and I didn't notice — in #4.
